name: ubuntu

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-linux:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      # https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: echo -e '[url "https://github.com/"]\n  insteadOf = "git@github.com:"' >> ~/.gitconfig
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Install Metanorma gem
        run: gem install metanorma-cli
      - name: Install LaTeXML
        run: |
          curl -L http://cpanmin.us | sudo perl - App::cpanminus
          sudo apt-get install -y libxml2-dev libxslt-dev
          sudo cpanm --notest XML::LibXSLT@1.96 git://github.com/brucemiller/LaTeXML.git@9a0e7dc5
      - name: Tests
        run: |
          make all METANORMA_PREFIX=
