name: windows

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  test-windows:
    name: Test on Windows
    runs-on: windows-latest
    strategy:
      fail-fast: false
    steps:
      # https://github.com/actions/checkout/issues/14#issuecomment-523916396
      - name: Fix up git URLs
        run: |
          echo '[url "https://github.com/"]' >> ~/.gitconfig
          echo '  insteadOf = "git@github.com:"' >> ~/.gitconfig
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: Use Ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6'
          architecture: 'x64'
      - name: Install Metanorma gem
        run: gem install metanorma-cli
      - name: Install dependencies
        shell: cmd
        run: |
          cinst --no-progress -y imagemagick.tool make gnuwin32-coreutils.install
          cinst --no-progress -y latexml --pre 
      - name: Tests
        run: make all SHELL=cmd METANORMA_PREFIX=
